delete from afu_gewaesserschutz.gwszonen_rechtsvorschriftgwsareal;
delete from afu_gewaesserschutz.gwszonen_rechtsvorschriftgwszone;
delete from afu_gewaesserschutz.gwszonen_gwsareal;
delete from afu_gewaesserschutz.gsbereiche_gsbereich;
delete from afu_gewaesserschutz.gwszonen_gwszone;
delete from afu_gewaesserschutz.gwszonen_dokument;
delete from afu_gewaesserschutz.gwszonen_status;